server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql:///datajpadb
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform:  org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update